# Helpful: https://tmuxcheatsheet.com/

bind-key R 'source-file ~/.tmux.conf; display-message "Configuration reloaded"'

setw -g mode-keys vi
set -g status-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

bind-key x kill-pane

# Makes TMUX compatible with powerlevel10k
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

# Window indexes start at 1 (the default is INSANE)
set -g base-index 1
set -g pane-base-index 1

set-option -g status-interval 1
set-option -g status-style bg=black
set-option -g status-style fg=white
set-window-option -g window-status-current-style bg=blue,fg=white,bold

set -g status-left '#[fg=green][#S] #{?pane_in_mode,#[fg=cyan]COPY ,}#[fg=green]#{b:pane_current_path} #[default]'
set -g status-right '%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'

set-option -g repeat-time 0
